server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip Compression for performance
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets aggressively
    location ~* \.(?:css|js|jpg|svg|png|json)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
